version: '2'
services:
  api:
    build: .
    command: npm start
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/events-api
    - /usr/src/events-api/node_modules
    links:
    - db
  db:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - /data/db2/:/data/db/
    command: /usr/bin/mongod --smallfiles
