version: '2'
services:
  api:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/events-api
    links:
    - db
  db:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - /data/db2/:/data/db/
    command: /usr/bin/mongod --smallfiles
